package com.junkycars.rest

import org.json4s.{DefaultFormats, Formats}
import org.scalatra.json.JacksonJsonSupport
import org.scalatra.{CorsSupport, ScalatraFilter}

class ServicesEndPoint extends ScalatraFilter with  CorsSupport with JacksonJsonSupport {

  get("/cars") {
    <p>
      This response was generated by the filter.  By default, the
      <code>notFound</code> action of the filter delegates to the
      next item in the filter chain.  This is ideal for delegating
      to static resources or legacy servlets.
    </p>
  }

  override protected implicit def jsonFormats: Formats = DefaultFormats
}
